---
apiVersion: v1
kind: Secret
metadata:
  name: web-secret
type: Opaque
data:
  username: YWRtaW4=         # "admin" codificado en base64
  password: c2VjcmV0MTIz     # "secret123" codificado en base64

